language: python
python:
- '2.7'
- '3.5'
- '3.6'
services:
- docker
before_install:
- docker pull postgres:9.4
- docker pull postgres
install:
- pip install pip-tools
- pip-compile --upgrade -o requirements-pinned.txt requirements.txt requirements_secrets.in requirements_prometheus.in
- pip-compile --upgrade -o test-requirements-pinned.txt requirements-pinned.txt requirements_dev.txt
- cat requirements-pinned.txt
- pip install -r test-requirements-pinned.txt
- pip install 'pyscaffold<3.0'
- pip install coveralls
- pip install -e .[docker]
- pip freeze
script:
- . setup_integration_test_docker.sh
- py.test
after_success:
- coveralls
deploy:
  provider: pypi
  user: BYPyPi
  password:
    secure: U6xBX+5D6GnQUXhwx6IbQcAgkZ2HA9vLY1rKVevsokek1wENADW+1hatRl7KgwN8UribXtJhb/rr6zBeY3fFLKwY3/JciCN8cIm90EaCF49RKR86kdojqb/9o7Vj9hyjEm3DYRkbbH11YdnAyO9DJxVzUOtKm7FlMM9vE/pKwEXemwMeKKkzFCk5T8CbMdzOslMdR9ghXqiwO3mEH6YqpgwcmTRY8J77nFhI4173aQ3tCcZcji79Z9SdiFaFapLTIJFZgVyZWwHR7bG9H1UlRk+ANtYIDU+0Ibr6c9IsOovFHDLFH+Fxr23aMTSD/EbBkQUL19l18HWi37fpLNVJpjEIVnBoTrbAgzR3dC/3OEZUFWnAX6wmzwAj83gABI9b+clnXz7BEPAybIhrl2COTuzHuHgzUD7ZEJJ787RiZ59Q4NwJ6jjapm/WAUl5/fBZM040mKVyAdaK0C2hS5QJuUts/0Le+iwxy5qv+7eapJcQoj9Hsc4LAYAOb2VSAIQtbEGU3X46kN3irx0o15A2Jmszu+rTpC875a2dCoMiv7F9nwNDhQrVvp5OVv4445/BZur2s9IIu69dKaUMRmKrFI3GnC+TdF7Tx6XV0i3V/Oj7mXzu7YEjEPhCOYAePncNKmOztHp9HwJaNyWTXgs8ZtGsS+KFH8FBMeB5eO+xWq0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
