language: python
python:
- '2.7'
services:
- docker
- postgresql
addons:
  postgresql: "9.4"
env:
- PGDATABASE=postgres PGUSER=postgres PGPASSWORD=postgraas_password
before_install:
- docker pull postgres:9.4
- psql -c "alter user $PGUSER with password '$PGPASSWORD';" -U postgres
- sudo sed -ie 's/trust/md5/g' /etc/postgresql/9.4/main/pg_hba.conf
- sudo service postgresql restart
install:
- pip install pip-tools
- pip-compile --upgrade -o requirements-pinned.txt requirements.txt requirements_secrets.in requirements_prometheus.in
- pip-compile --upgrade -o test-requirements-pinned.txt requirements-pinned.txt requirements_dev.txt
- cat requirements-pinned.txt
- pip install -r test-requirements-pinned.txt
- pip install pyscaffold
- pip install coveralls
- pip install -e .[docker]
- pip freeze

script: py.test
after_success:
- coveralls
deploy:
  provider: pypi
  user: sebastianneubauer
  password:
    secure: AwbSrSt2gVm8FhXKMOdtmwifnNwjUbuLeJdpMnIXMLkpzEAMAoJPPkn4+hsvaC9HpKZKl/CMo94ZZ+39lQ1n8C+7LvhcvR6QEBnSS44PuTZb7cb//WEexHpJx2uqP36GA7OAcyQ1fLQ10sMU1xqxFWvHrboafqHt9i5U30HpWwSwZK8EsEHfAzJGyCaRxqgyuUZUNPhzN6JFfmrIuHWXEl85z7TiTrnBT7tsSFj242qO/XNrq7PzhLRxV+e6HXIDTlCBY3TVg7FcDacIAZOWnJn8ixW/uZz2Cg9Etjl1E5PauCAo/mOzNSp4MoL+EsTlhY6eIOYOBt1nrd1UkZeWZzVvVsSMwgkN5erJ/Gd/e63UlcFB0Gr5g4s+Gl/yLTZpLSL+643Adn67IK/JkkynkvMvePVDpIxgSaAzQYllCYrVi7Hy7OugYeH907cOhGzjChi3uHQR+tWxT26fL6+CQCeVW5O5sqm08HUYBbDit8BRdjhu4keG8p4xoJ4GH3Nffo4+IDU2ANpoxVgJf5+o9TACpKR6yTYI2Jq02d+CBvJbqmNTtC6wpSDianviHDxNNipbJJtIbtCgS3ERtmxsPUBWvYaFAEYncNwYC/h7b59VUjXGgzx/E55j0T61xfn2EQvFSo7Y+z0MNMmFBEzAp86GFPkWUNRywuuPxeHFQFY=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
